#include"testOramAccess.h"
#include"util.h"
#include<stdio.h>
#include<stdlib.h>
#include<obliv.h>

void showUsage(const char* exec)
{
  fprintf(stderr,"Usage: %s -- <port> <type> <initial data>\n"
                 "   or: %s <remote-server> <port> <type> <indices>\n"
                 "Where:\n"
                 "  type         - ORAM type, one of 'lin', 'sqrt', 'ckt'\n"
                 "  initial data - either a list of integers\n"
                 "                 or --auto=n for autogenerated values\n"
                 "  indices      - either a list of positions to access\n"
                 "                 or --auto=n for random positions\n",
                 exec,exec);
  exit(1);
}
// Populate the entire array of given size with values in range [0,lim)
void populateArray(int dest[],int size,int lim)
{
  int i;
  for(i=0;i<size;++i) dest[i]=rand()%lim;
}

// Exchange private inputs so we can verify output correctness
void exchangeInputs(TestOramAccessIO* args,int accn,int n)
{
  if(ocCurrentParty()==1) args->indices = malloc(accn*sizeof(int));
  else args->content = malloc(n*sizeof(int));
  int i;
  for(i=0;i<accn;i++) args->indices[i]=ocBroadcastInt(args->indices[i],2);
  for(i=0;i<n;++i) args->content[i]=ocBroadcastInt(args->content[i],1);
  args->detailedOut = (  ocBroadcastBool(args->detailedOut,1)
                      && ocBroadcastBool(args->detailedOut,2));
}

int main(int argc,char* argv[])
{
  bool autoSize=false,autoAccess=false;
  ProtocolDesc pd;
  TestOramAccessIO io;
  int i,me;
  srand(time(0));

  // Parse parameters
  if(argc<5) showUsage(argv[0]);
  else if(strcmp(argv[1],"--")==0)
  { // Get ORAM size
    if(strncmp(argv[4],"--auto=",strlen("--auto="))==0)
    { autoSize=true;
      if(sscanf(argv[4]+strlen("--auto="),"%d",&io.size)!=1) showUsage(argv[0]);
    }
    else io.size=argc-4;
    // Populate with initial content
    io.content=malloc(sizeof(int)*io.size);
    if(autoSize) populateArray(io.content,io.size,RAND_MAX);
    else for(i=0;i<io.size;++i)
      if(sscanf(argv[i+4],"%d",io.content+i)!=1) showUsage(argv[0]);
    me=1;
  }else
  { // Get access count
    if(strncmp(argv[4],"--auto=",strlen("--auto="))==0)
    { autoAccess=true;
      if(sscanf(argv[4]+strlen("--auto="),"%d",&io.size)!=1) showUsage(argv[0]);
    }else io.size=argc-4;
    // Get access indices
    io.indices=malloc(sizeof(int)*io.size);
    if(autoAccess) populateArray(io.indices,io.size,io.size);
    else for(i=0;i<io.size;++i) if(sscanf(argv[i+4],"%d",io.indices+i)!=1)
      showUsage(argv[0]);
    me=2;
  }
  io.type = (strcmp(argv[3],"lin")==0?oramTypeLin:
            (strcmp(argv[3],"sqrt")==0?oramTypeSqrt:
             oramTypeCkt));
  io.detailedOut = !(autoAccess||autoSize);

  // Connect and execute protocol
  connectOrDie(&pd,argv[1],argv[2]);
  setCurrentParty(&pd,me);
  execYaoProtocol(&pd,testOramAccess,&io);

  // Cleanup, print and verify
  bool outputok=true;
  for(i=0;i<io.size;++i) if(io.outputs[i]!=io.content[io.indices[i]])
  { if(outputok)
    { printf("Test failed. Position(s):");
      outputok=false;
    }
    printf(" %d",i);
  }
  if(outputok) printf("Checks passed\n"); else printf("\n");
  if(io.detailedOut)
  { for(i=0;i<io.size;++i) printf("%d ",io.outputs[i]);
    printf("\n");
  }
  free(io.outputs);
  free(io.content);
  free(io.indices);
  cleanupProtocol(&pd);
  return 0;
}
