/* Common parts:
   * Parse server:port, connect TCP
   * Parse <linear|sqrt|ckt>
   * Initialize with zeroed/garbage ORAMs (utils)
   * Runtime reporting
   Uncommon parts:
   * Concrete inputs (test mode)
   * Input size, test count (bench mode)
   Todo:
   * Write search/bfs, refactor later
   * Tons of boilerplate, to refactor later

   ./search test :1234 -t lin 3 2 4 4 9 2
   # mode and netspec can be flipped
   # '-x' options can appear pretty much anywhere
   ./search :1234 test 3 9 2 8 3 4 -t lin
   ./search bench server:1234 --type=sqrt -z 499 -c 100
   Bench shows timing, test uses return value or one-line error.

   There should be a "mismatched params" error.
   */

#include<stdbool.h>

#include<util.h>
#include"search.h"

const char cmdUsage[] =
    "Usage: search test        :port <options> <haystack>\n"
    "   or: search test  server:port <options> <needles>\n"
    "   or: search bench --size=# --axcount=# :port\n"
    "   or: search bench                server:port\n"
    "\n"
    "Options:\n"
    "  -t <type>         ORAM type. One of linear, sqrt, or ckt.\n"
    "  --oramtype=<type>\n"
    "\n"
    "Test mode:\n"
    "  Runs ORAM search on manually entered data. The search is followed by\n"
    "  a plaintext  evaluation that checks correctness.\n"
    "  <haystack>        A sequence of integers. Must be sorted.\n"
    "  <needle>          A sequence of integers to search for.\n"
    "  --showResult, +o  Show output locations (default).\n"
    "  --hideResult, -o  Don't show output locations.\n"
    "\n"
    "Benchmark mode:\n"
    "  --size=n, -z n    Number of integers in autogenerated array\n"
    "  --axcount=n, -c n Number of random searches to perform\n"
    ;

bool searchCmdSizeCount(CmdParseState* s,void* vio)
{
  SearchIO* io=vio;
  return cmdParseSingleInt(s,'z',"size",&io->n,-1)
      && cmdParseSingleInt(s,'c',"axcount",&io->axc,-1);
}

int main(int argc,char *argv[])
{
  SearchIO io = {.data=NULL,.indices=NULL,.outputs=NULL,.n=-1,.axc=-1};
  ProtocolDesc pd;
  CmdParseState ps = cmdParseInit(argc,argv);
  cmdSetUsage(cmdUsage);
  cmdParseCommon(&ps,searchCmdSizeCount,&io);
  // Parse my own params, --size, --axcount, inputs
  cmdConnectOrDie(&pd);
  return 0;
}
